version: '3.8'

services:
  api-python-todo:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://admin:admin_password@mongodb:27017
      - DATABASE_NAME=mydatabase
    volumes:
      - .:/app
    depends_on:
      - mongodb
    networks:
      - todo-network

  mongodb:
    image: mongo:latest
    container_name: mongo-container
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin_password
    volumes:
      - mongo-data:/data/db
    networks:
      - todo-network

volumes:
  mongo-data:
    driver: local

networks:
  todo-network:
    driver: bridge
